### ISSUE TITLE
Long-running processes are ok?

### ISSUE THREAD

**Issue by dsandber** [tomykaira/clockwork#111]
Hi,

Something the main document doesn't address is what happens if long-run tasks are put directly into clockwork with no queueing. While I understand this isn't recommended, it makes sense in some cases such as when there's no harm if a task gets delayed.

Will clockwork work properly (no exceptions, warnings, errors, ...) if I have it execute a long-lived task that causes another scheduled task to execute later than it would otherwise?

I'd suggest adding the answer to the readme.

Thanks!

-Dan

**Comment by tomykaira** [comment]
035f2c2 Thanks for sincere suggestion.
