### ISSUE TITLE
Question Reliable (Quick testing on Heroku)

### ISSUE THREAD

**Issue by nmccready** [tomykaira/clockwork#131]
Has anyone developed a plugin so I can test my clockwork/cron job on demand on heroku? I just want to make sure the darn thing is working on the real environment without needing the time to pass. I have written specs and an away to run a job on demand from the command line. My first thoughts would be to add a restful endpoint to kick of the routine, but it would be nice if heroku just had a button to init this. Then I would not have to worry about the security of the restful endpoint.

**Comment by tomykaira** [comment]
The question seems not about clockwork, then you have more chance on StackOverflow or heroku community.
Sorry that I could not help.
