### ISSUE TITLE
Use of :if with database events

### ISSUE THREAD

**Issue by adrianpcastro** [tomykaira/clockwork#153]
I am attempting to use Clockwork to create scheduled jobs in a day of the month. For example, I want to start a job the 5th of May every year. I try to use the :if parameter like a method in my ActiveRecord  model (like frequency in the example), but it seems that the if parameter is not called with database events.

def if
    lambda { |t| t.day == 1 && t.month == 5}
end

how can I do it?

**Comment by robisenberg** [comment]
Hi @adrianpcastro, thanks for your question.

See my comments in #147 and #113. We don't currently support the `:if`parameter, but you can achieve what you want by following the instructions in my replies to those Github issues.

Having said that, as stupid as it sounds, doing what you've done in your code above never occurred to me, but actually seens like the perfect solution I've been searching for on how best to support arbitrary `:if`conditions for database events, namely, the database event model can implement a method similar to `if` as you've done (it probably can't be called that as `if` is a reserved word?) which can be used to determine, with any arbitrary, app-specific logic, whether the event should be run or not when `clcokwork` is about to run it. The values you've currently hard-coded (the month and day of month) could even be stored in the database, but that's probably where you were headed.

So many thanks for this inspired solution (I can't quite believe I was so stupid to miss it!) If you need this feature urgently, follow the instructions in the issues I linked to above, but I'll try to implement the feature properly along the lines you suggested when I get a chance.

Thanks again.

**Comment by robisenberg** [comment]
Hey @adrianpcastro. Apologies for the delay - but we finally got this one in!

Thanks for your input - it was a big help.
