### ISSUE TITLE
Upgrading dependencies especially around tests

### ISSUE THREAD

**Issue by robisenberg** [tomykaira/clockwork#161]
@tomykaira Following on from #160.

I notice that we're using an old version of `MiniTest` and still depending on`Test::Unit` - presumably to keep compatibility with `ActiveSupport 3` (we use this for `TZ` support, but also `ActiveSupport::TestCase` in the tests.

I'm wondering whether the test setup could be improved/updated. Would it be possible to remove support for `ActiveSupport 3`? If so, perhaps we can just update to the latest version of `MiniTest` and remove `Test::Unit` etc.

Are you ok with me having a go at this?

**Comment by summera** [comment]
@robisenberg Started fixing up the tests in https://github.com/tomykaira/clockwork/pull/174.

Any idea if this project is still being actively maintained?

**Comment by robisenberg** [comment]
@tomykaira I understand you're busy with other things, but really need some quick input from you on where we go with Clockwork going forwards. (I'm hoping you're getting notifications about these issue updates as I have no other way of contacting you!)

Are you still planning on actively maintaining it? If not (which is totally cool - I get the pressures of Open Source, and struggling to find time etc) perhaps we can agree a plan? Do you want someone else to take over responsibility for the project?

I've been reluctant to use my maintainer privileges to fix issues, or merge pull requests from people because I didn't want to overstep my bounds (I was brought on to support the database-backed events that I implemented). Also, it's your repo, so I didn't want to mess with it without your approval.

It would be great if you could either give me the OK to continue to make changes to the repo as I see fit (and possibly enlist other maintainers) or perhaps you'd consider allowing a fork and making that the official Repo?

Sorry, I'm not trying to drag you in to doing more work, but just hoping you can unblock us and help us arrive at a way forwards.

Thanks!

**Comment by robisenberg** [comment]
@koriroys do you have any thoughts or know how to get hold of @tomykaira?

**Comment by koriroys** [comment]
@robisenberg no idea. A bit ironic to not have time to work on clockwork. :smile: 

Also, don't worry about overstepping bounds. If something needs doing, go ahead and do it. No fear.

**Comment by robisenberg** [comment]
@koriroys :smile: thanks, I appreciate you saying that. I feel much better moving things forwards if I'm not taking unilateral action!

**Comment by robisenberg** [comment]
Resolved by #174
