### ISSUE TITLE
Support for day-of-month

### ISSUE THREAD

**Issue by ballcheck** [tomykaira/clockwork#171]
Hi,

I have been trying to get monthly clockwork events working with database events using the advice given here https://github.com/tomykaira/clockwork/issues/147 but with varied results.

Example: I'd like my event to run on the 1st of each month at 4:30am

If you have a database event with :at => "4:30", then `At#ready?` returns true for the event every day at 4:30.

The frequency is set to 1 month, but if this is the first time the event has been run since clockwork started then `Event#elapsed_ready` returns true, causing `Event#run_now?` to return true. We end up with `Event#run` being called and `@last` being set to now (7th Jan)

In the block passed to `sync_database_events` we decide not to run the job because it is not the first of the month.

A few weeks later, when it gets to 1st Feb and 4:30 `Event#elapsed_ready` returns false because it has been less than a month since 7th Jan

Hope this makes sense!

Ideally I would like `At` to support day-of-month (mday) as well as wday, hour, min. Happy to help with this.

Thanks.

**Comment by kevin-j-m** [comment]
I believe the documentation for the [if parameter](https://github.com/tomykaira/clockwork#if) includes an example of running a job on the first day of the month. If you combine that with your time requirement, does that solve your use case?

I'm thinking something like this:
```ruby
Clockwork.every(1.day, 'myjob', :if => lambda { |t| t.day == 1 }, :at => "4:30")
```

**Comment by ballcheck** [comment]
Hi @kevin-j-m 

I am trying to get this working with database events, as described here: https://github.com/tomykaira/clockwork/issues/147

**Comment by kevin-j-m** [comment]
Sorry @ballcheck, I missed that you clearly stated you were working with database events. My bad. Unfortunately I have no experience with database events so I can't help you out. Best of luck!

**Comment by ballcheck** [comment]
Poke.

**Comment by ballcheck** [comment]
This feature is now in place. Whoop!
https://github.com/tomykaira/clockwork/pull/180
