### ISSUE TITLE
“at:” time not triggering events

### ISSUE THREAD

**Issue by jonahx** [tomykaira/clockwork#184]
My clockwork `script.rb` looks like:

    module Clockwork
      configure do |config|
        config[:sleep_timeout] = 1
        config[:tz] = 'EST'
        config[:max_threads] = 15
        config[:thread] = true
      end

      handler do |job|
        puts 'job triggered'
      end

      every(1.day, 'test', at: '13:00')
    end

If I run `clockwork script.rb` on my laptop, which is in EST time, at '12:58', and then wait until '13:01', no event is ever triggered.

Am I misunderstanding the correct usage?

Thanks.

**Comment by prasadsurase** [comment]
@jonahx I tried to reproduce the error by only replacing the timezone and the 'at:' time but wasnt able to. The puts statement was executed as expected. I used the version '2.0.0' with ruby 2.2.2p95 on OSX. Are you still able to reproduce the same error? If yes, could you please add more details?

**Comment by jonahx** [comment]
It's working for me now on heroku, go ahead and close.  Thanks.
