### ISSUE TITLE
Run task only in window

### ISSUE THREAD

**Issue by fabdelgado** [tomykaira/clockwork#185]
Hello need clockwork run through a task in a window at the 8:00 a.m. to 20AM.

I use it well but today is because infeciente always running.

   every (15.minutes, 'Forecast Parser') {
     `Rake forecast: parser`
   }

**Comment by fabdelgado** [comment]
How can I set a cron to run every 15 minutes  between 8 am and 20 pm. Is this possible?

**Comment by sandstrom** [comment]
Perhaps this is better suited for [Stackoverflow](http://stackoverflow.com/).

**Comment by fabdelgado** [comment]
OK, thankyou.
